steps:
  # Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/pixel-editor-server:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/pixel-editor-server:latest',
      '.'
    ]

  # 이미지를 Container Registry에 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/pixel-editor-server:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/pixel-editor-server:latest']

  # Cloud Run에 배포
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'pixel-editor-server',
      '--image', 'gcr.io/$PROJECT_ID/pixel-editor-server:$COMMIT_SHA',
      '--region', 'asia-northeast3',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '3001',
      '--memory', '1Gi',
      '--cpu', '1',
      '--min-instances', '0',
      '--max-instances', '10',
      '--concurrency', '80',
      '--timeout', '300',
      '--set-env-vars', 'NODE_ENV=production'
    ]

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1200s'